#!/bin/bash

if [ "${1}" == "" ] ; then
	echo ""
  echo "Usage: fslvbm_get_voxel_info <subjects> <rois> <roibasedir> <imagepostfix>"
  echo ""
  echo "       <subjects>     : file with subject IDs"
  echo "       <rois>         : file with ROIs"
  echo "       <roibasedir>   : directory containing ROIs"
  echo "       <imagepostfix> : postfix of subject image registered to study-specific"
  echo "                        or MNI template, for example"
  echo ""
  echo "                        <subjectid>_GM_to_template_GM_mod"
  echo ""
  echo "                        or"
  echo ""
  echo "                        <subjectid>_GM_to_MNI_mod"
  echo ""
  exit 1
fi

subjects=${1}
rois=${2}
roibasedir=${3}
imagepostfix=${4}

echo "`date` - extracting voxel values" >> timing.txt

mkdir -p output/values

for roi in `more ${roibasedir}/${rois}` ; do
	echo "echo \${2} \${1}" > tmp.sh
	echo "${FSLDIR}/bin/fslmeants -i output/\${2}${imagepostfix} -m ${roibasedir}/\${1} -o output/values/\${2}_\${1}_values.txt --showall" >> tmp.sh
	chmod a+x tmp.sh
	parallel -a ${subjects} ./tmp.sh ${roi}
	rm tmp.sh	
done

echo "`date` - done" >> timing.txt

more timing.txt