#!/bin/bash

pwd=$(pwd)
cd ${HOME}/development

for d in $(ls); do
	if [ -d ${d} ]; then
		cd $(pwd)/${d}
		if [ -d $(pwd)/.git ]; then
			changes=$(git status -s)
			if [ "${changes}" != "" ]; then
				git add -A; git commit -m "Saving work"; git push
			fi
		fi
		cd ..
	fi
done

cd ${pwd}