#!/usr/bin/env python

import os

def run():
    base = '/Users/Ralph/development'
    dirs = os.listdir(base)
    for d in dirs:
        d = os.path.join(base, d)
        if not os.path.isdir(d):
            continue
        if not os.path.isdir(os.path.join(d, '.git')):
            continue
        os.system('cd {}; git add -A; git commit -m "Saving work"; git pull'.format(d))

if __name__ == '__main__':
    run()

