#!/bin/bash

ls ~/development > /tmp/dirs.txt
for dir in `more /tmp/dirs.txt`; do
    if [ -d ~/development/${dir}/.git ]; then
        pwd=`pwd`
        cd ~/development/${dir}
        git status > /tmp/status.txt
        cd ${pwd}
        result=`diff ${pwd}/status.txt /tmp/status.txt`
        if [ "${result}" == "" ]; then
            echo "No changes"
        fi
    fi
done
